import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import './styles.css';

const storedId = () => { const key = 'jinxo-player-id'; let id = sessionStorage.getItem(key); if (!id) { id = crypto.randomUUID(); sessionStorage.setItem(key, id); } return id; };
const initialAnswers = ['', '', ''];
function emit(socket, event, payload) { return new Promise(resolve => socket.emit(event, payload, resolve)); }
function App() {
  const socketRef = useRef(); const playerId = useMemo(storedId, []);
  const [name, setName] = useState(sessionStorage.getItem('jinxo-name') ?? ''); const [code, setCode] = useState(''); const [room, setRoom] = useState(); const [message, setMessage] = useState(''); const [answers, setAnswers] = useState(initialAnswers); const [sent, setSent] = useState(false); const [now, setNow] = useState(Date.now());
  useEffect(() => {
    const socket = io(); socketRef.current = socket; socket.on('room:update', setRoom);
    socket.on('connect', async () => {
      const savedCode = sessionStorage.getItem('jinxo-room-code'); const savedName = sessionStorage.getItem('jinxo-name');
      if (savedCode && savedName) { const result = await emit(socket, 'room:join', { code: savedCode, name: savedName, playerId }); if (result?.room) setRoom(result.room); }
    });
    return () => socket.close();
  }, [playerId]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 500); return () => clearInterval(timer); }, []);
  const join = async (type) => { const trimmed = name.trim(); if (!trimmed) return setMessage('닉네임을 입력해 주세요.'); sessionStorage.setItem('jinxo-name', trimmed); const result = await emit(socketRef.current, type === 'create' ? 'room:create' : 'room:join', type === 'create' ? { name: trimmed, playerId } : { name: trimmed, code, playerId }); if (result?.error) setMessage(result.error); else { sessionStorage.setItem('jinxo-room-code', result.room.code); setRoom(result.room); setMessage(''); } };
  const current = room?.players.find(p => p.id === playerId); const remaining = room?.deadline ? Math.max(0, Math.ceil((room.deadline - now) / 1000)) : 0;
  const submitAnswers = async () => { const result = await emit(socketRef.current, 'answers:submit', { code: room.code, playerId, answers }); if (result?.error) setMessage(result.error); else setSent(true); };
  useEffect(() => { if (room?.phase === 'answering') { setAnswers(initialAnswers); setSent(false); } }, [room?.round, room?.phase]);
  if (!room) return <Lobby name={name} setName={setName} code={code} setCode={setCode} message={message} onCreate={() => join('create')} onJoin={() => join('join')} />;
  return <main className="app-shell"><header><div className="brand">JIN<span>X</span>O <small>온라인 보드게임</small></div><div className="round">TOPIC {Math.max(0, room.round + 1)} / 3</div><div className="timer">{room.phase === 'answering' ? <><b>{remaining}</b>초</> : room.phase === 'results' ? 'GAME OVER' : '판정 중...'}</div></header><div className="players">{room.players.map(p => <div className={'avatar ' + (!p.connected ? 'offline' : '')} key={p.id}><strong>{p.name.slice(0, 1)}</strong><span>{p.name}{p.id === room.hostId ? ' ♛' : ''}</span></div>)}</div>{room.phase === 'lobby' ? <Waiting room={room} playerId={playerId} onStart={async () => { const result = await emit(socketRef.current, 'game:start', { code: room.code, playerId }); setMessage(result?.error ?? ''); }} /> : room.phase === 'results' ? <Results room={room} playerId={playerId} onRematch={async () => { const result = await emit(socketRef.current, 'game:rematch', { code: room.code, playerId }); setMessage(result?.error ?? ''); }} /> : <section className="game-layout"><div className="game-main"><article className="topic"><small>이번 주제 · 답 {room.round * 3 + 1}–{room.round * 3 + 3}번 칸</small><h1>{room.topic}</h1></article><Board board={current?.board ?? []} /><p className="rule-note">○ 1점 · ★ 2점 · X 0점 · 빙고 1줄 +{room.bonus}점</p></div><aside className="answer-panel">{room.phase === 'answering' ? <><h2>우리만의 답 3개!</h2><p>서로 다른 답을 적어 {room.round * 3 + 1}–{room.round * 3 + 3}번 칸에 채워요.</p>{answers.map((value, index) => <label key={index}><span>{index + 1}</span><input value={value} disabled={sent} maxLength="32" placeholder="답을 입력하세요" onChange={e => setAnswers(prev => prev.map((item, i) => i === index ? e.target.value : item))} /></label>)}<button disabled={sent} onClick={submitAnswers}>{sent ? '제출 완료!' : '답변 제출하기 →'}</button></> : <><h2>답을 비교하는 중!</h2><div className="burst">JINX!</div><p>모두의 마음이 통했는지 확인하고 있어요.</p></>}</aside></section>} {message && <p className="toast">{message}</p>}</main>;
}
function Lobby({ name, setName, code, setCode, message, onCreate, onJoin }) { return <main className="lobby"><div className="confetti a"/><div className="confetti b"/><section><div className="brand large">JIN<span>X</span>O <small>나랑 너랑!</small></div><h1>우리 둘만의<br/>빙고 게임</h1><p>같은 주제, 같은 마음. <br/>친구들과 실시간으로 즐겨요.</p><label>닉네임<input value={name} maxLength="16" placeholder="예: 지니" onChange={e => setName(e.target.value)} /></label><button onClick={onCreate}>새 게임 만들기</button><div className="join"><input value={code} maxLength="5" placeholder="초대 코드" onChange={e => setCode(e.target.value.toUpperCase())} /><button onClick={onJoin}>입장</button></div>{message && <p className="toast">{message}</p>}</section></main> }
function Waiting({ room, playerId, onStart }) { const host = room.hostId === playerId; return <section className="waiting"><div><small>초대 코드</small><h1>{room.code}</h1><p>친구에게 코드를 알려 주고 함께 입장하세요.</p></div><div className="waiting-players">{room.players.map(p => <span key={p.id}>{p.name}</span>)}</div>{host ? <button onClick={onStart}>게임 시작하기 →</button> : <p className="host-wait">방장이 게임을 시작하면 바로 출발해요!</p>}<p className="rule-note">2–7명 · 3개 주제 · 주제마다 답 3개 · 75초</p></section> }
function Board({ board }) { return <div className="board">{Array.from({ length: 9 }, (_, i) => { const cell = board[i]; return <div className={'cell ' + (cell?.mark ?? '')} key={i}><small>{i + 1}</small>{cell?.answer && <p>{cell.answer}</p>}{cell && <b aria-label={cell.mark}>{cell.mark === 'star' ? '★' : cell.mark === 'circle' ? '○' : '×'}</b>}</div>; })}</div> }
function Results({ room, playerId, onRematch }) { const sorted = [...room.players].sort((a, b) => b.score.points - a.score.points || b.score.lines - a.score.lines || b.score.stars - a.score.stars); return <section className="results"><div className="winner">{sorted[0]?.name} <span>WIN!</span></div><h1>마음이 통했어요!</h1><div className="rankings">{sorted.map((p, i) => <div key={p.id}><b>{i + 1}</b><span>{p.name}</span><strong>{p.score.points}점</strong><small>빙고 {p.score.lines} · 별 {p.score.stars}</small></div>)}</div>{room.hostId === playerId ? <button onClick={onRematch}>한 번 더 하기 →</button> : <p className="host-wait">방장이 재대결을 시작할 수 있어요.</p>}</section> }
createRoot(document.getElementById('root')).render(<App />);
