import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import './styles.css';

const storedId = () => { const key = 'jinxo-player-id'; let id = sessionStorage.getItem(key); if (!id) { id = crypto.randomUUID(); sessionStorage.setItem(key, id); } return id; };
const initialAnswers = ['', '', ''];
function emit(socket, event, payload) { return new Promise(resolve => socket.emit(event, payload, resolve)); }
function App() {
  const socketRef = useRef(); const playerId = useMemo(storedId, []);
  const [name, setName] = useState(sessionStorage.getItem('jinxo-name') ?? ''); const [code, setCode] = useState(''); const [room, setRoom] = useState(); const [message, setMessage] = useState(''); const [answers, setAnswers] = useState(initialAnswers); const [slots, setSlots] = useState([null, null, null]); const [activeAnswer, setActiveAnswer] = useState(0); const [sent, setSent] = useState(false); const [now, setNow] = useState(Date.now()); const [tutorialOpen, setTutorialOpen] = useState(false);
  useEffect(() => {
    const socket = io(); socketRef.current = socket; socket.on('room:update', setRoom);
    socket.on('connect', async () => {
      const savedCode = sessionStorage.getItem('jinxo-room-code'); const savedName = sessionStorage.getItem('jinxo-name');
      if (savedCode && savedName) { const result = await emit(socket, 'room:join', { code: savedCode, name: savedName, playerId }); if (result?.room) setRoom(result.room); }
    });
    return () => socket.close();
  }, [playerId]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 500); return () => clearInterval(timer); }, []);
  const join = async (type) => { const trimmed = name.trim(); if (!trimmed) return setMessage('닉네임을 입력해 주세요.'); sessionStorage.setItem('jinxo-name', trimmed); const result = await emit(socketRef.current, type === 'create' ? 'room:create' : 'room:join', type === 'create' ? { name: trimmed, playerId } : { name: trimmed, code, playerId }); if (result?.error) setMessage(result.error); else { sessionStorage.setItem('jinxo-room-code', result.room.code); setRoom(result.room); setMessage(''); } };
  const current = room?.players.find(p => p.id === playerId); const remaining = room?.deadline ? Math.max(0, Math.ceil((room.deadline - now) / 1000)) : 0;
  const submitAnswers = async () => { const result = await emit(socketRef.current, 'answers:submit', { code: room.code, playerId, answers, slots }); if (result?.error) setMessage(result.error); else setSent(true); };
  const shareAnswer = async slot => { const result = await emit(socketRef.current, 'answer:share', { code: room.code, playerId, slot }); if (result?.error) setMessage(result.error); };
  const nextSharing = async () => { const result = await emit(socketRef.current, 'sharing:next', { code: room.code, playerId }); if (result?.error) setMessage(result.error); };
  const selectSlot = slot => {
    if (sent) return;
    const selectedIndex = slots.indexOf(slot);
    if (selectedIndex >= 0) return setActiveAnswer(selectedIndex);
    setSlots(previous => previous.map((value, index) => index === activeAnswer ? slot : value));
  };
  useEffect(() => { if (room?.phase === 'answering') { setAnswers(initialAnswers); setSlots([null, null, null]); setActiveAnswer(0); setSent(false); } }, [room?.round, room?.phase]);
  if (!room) return <><Lobby name={name} setName={setName} code={code} setCode={setCode} message={message} onCreate={() => join('create')} onJoin={() => join('join')} onTutorial={() => setTutorialOpen(true)} />{tutorialOpen && <Tutorial onClose={() => setTutorialOpen(false)} />}</>;
  const ruleNote = room.largeRoom ? '10인 규칙 · 2–3명 ★ 2점 · 4–5명 ○ 1점 · 6명+ ! 0점' : `○ 1점 · ★ 2점 · X 0점 · 빙고 1줄 +${room.bonus}점`;
  const sharing = room.sharing; const selectedPlayer = sharing?.selected && room.players.find(player => player.id === sharing.selected.playerId); const isPresenter = sharing?.currentPlayerId === playerId;
  return <main className="app-shell"><header><div className="brand">JIN<span>X</span>O <small>온라인 보드게임</small></div><div className="round">TOPIC {Math.max(0, room.round + 1)} / 3</div><div className="timer">{room.phase === 'answering' ? <><b>{remaining}</b>초</> : room.phase === 'sharing' ? '답 공유 중' : room.phase === 'results' ? 'GAME OVER' : '다음 주제 준비'}</div></header><div className="players">{room.players.map(p => <div className={'avatar ' + (!p.connected ? 'offline' : '')} key={p.id}><strong>{p.name.slice(0, 1)}</strong><span>{p.name}{p.id === room.hostId ? ' ♛' : ''}</span></div>)}</div>{room.phase === 'lobby' ? <Waiting room={room} playerId={playerId} onStart={async () => { const result = await emit(socketRef.current, 'game:start', { code: room.code, playerId }); setMessage(result?.error ?? ''); }} onTopics={async topics => { const result = await emit(socketRef.current, 'room:topics', { code: room.code, playerId, topics }); setMessage(result?.error ?? ''); return !result?.error; }} /> : room.phase === 'results' ? <Results room={room} playerId={playerId} onRematch={async () => { const result = await emit(socketRef.current, 'game:rematch', { code: room.code, playerId }); setMessage(result?.error ?? ''); }} /> : <section className="game-layout"><div className="game-main"><article className="topic"><small>{room.phase === 'sharing' ? '답 공유 · 보드에서 내 답 하나를 골라 읽기' : '이번 주제 · 빈 칸 3곳에 답을 배치'}</small><h1>{room.topic}</h1></article><Board board={current?.board ?? []} selectedSlots={room.phase === 'answering' ? slots : []} onSelect={room.phase === 'answering' ? selectSlot : undefined} onShare={room.phase === 'sharing' && isPresenter && !sharing.selected ? shareAnswer : undefined} round={room.round} showMarks={room.phase === 'results'} /><p className="rule-note">{ruleNote}</p></div><aside className="answer-panel">{room.phase === 'answering' ? <><h2>답 3개를 배치해요!</h2><p>각 답을 적고, 비어 있는 보드 칸을 하나씩 골라 주세요. 답은 최대 두 어절이며 이미 쓴 답은 다시 쓸 수 없어요.</p>{answers.map((value, index) => <label className={activeAnswer === index ? 'active-answer' : ''} key={index}><span>{index + 1}</span><div><small>{slots[index] === null ? '보드에서 빈 칸을 선택하세요' : `${slots[index] + 1}번 칸 선택됨`}</small><input value={value} disabled={sent} maxLength="24" placeholder="두 어절 이하 답" onFocus={() => setActiveAnswer(index)} onChange={e => setAnswers(prev => prev.map((item, i) => i === index ? e.target.value : item))} /></div></label>)}<button disabled={sent} onClick={submitAnswers}>{sent ? '제출 완료!' : '답변 제출하기 →'}</button></> : room.phase === 'sharing' ? <SharingPanel sharing={sharing} selectedPlayer={selectedPlayer} isPresenter={isPresenter} onNext={nextSharing} /> : <><h2>다음 주제로!</h2><div className="burst">JINX!</div><p>이번 주제 답을 기록했어요. 곧 다음 주제가 시작됩니다.</p></>}</aside></section>} {message && <p className="toast">{message}</p>}</main>;
}
function Lobby({ name, setName, code, setCode, message, onCreate, onJoin, onTutorial }) { return <main className="lobby"><div className="confetti a"/><div className="confetti b"/><section><div className="brand large">JIN<span>X</span>O <small>나랑 너랑!</small></div><h1>우리 둘만의<br/>빙고 게임</h1><p>같은 주제, 같은 마음. <br/>친구들과 실시간으로 즐겨요.</p><button className="how-to" onClick={onTutorial}>✦ 처음이라면? 게임 방법 보기</button><label>닉네임<input value={name} maxLength="16" placeholder="예: 지니" onChange={e => setName(e.target.value)} /></label><button onClick={onCreate}>새 게임 만들기</button><div className="join"><input value={code} maxLength="5" placeholder="초대 코드" onChange={e => setCode(e.target.value.toUpperCase())} /><button onClick={onJoin}>입장</button></div>{message && <p className="toast">{message}</p>}</section></main> }
const tutorialSteps = [{ title: '방을 만들고 친구를 초대해요', text: '닉네임을 입력해 새 게임을 만들면 5자리 초대 코드가 생겨요. Zoom 채팅으로 친구에게 알려 주세요.', view: 'lobby' }, { title: '답 3개를 빈 칸에 자유롭게 배치해요', text: '모든 플레이어가 같은 주제에 답 3개를 씁니다. 각 답은 비어 있는 3×3 보드 칸 하나를 골라 배치해요. 이미 보드에 쓴 답은 다른 주제에서도 다시 쓸 수 없어요.', view: 'answers' }, { title: '차례대로 답 하나를 읽고 함께 확인해요', text: '참가자가 돌아가며 이번 주제 답 하나를 골라 읽습니다. 세 답을 모두 공유한 뒤에 일치한 답과 빙고 점수를 확인해요.', view: 'board' }];
function Tutorial({ onClose }) { const [step, setStep] = useState(0); const current = tutorialSteps[step]; return <div className="tutorial-backdrop" role="dialog" aria-modal="true" aria-label="게임 방법"><section className="tutorial"><button className="tutorial-close" aria-label="게임 방법 닫기" onClick={onClose}>×</button><small>JINXO START GUIDE · {step + 1} / {tutorialSteps.length}</small><div className={'tutorial-shot ' + current.view}>{current.view === 'lobby' ? <><b>초대 코드</b><strong>JINXO</strong><span>지니 · 민수 · 유나</span></> : current.view === 'answers' ? <><b>이번 주제</b><strong>밤에 먹고 싶은 야식?</strong><i>1. 치킨</i><i>2. 라면</i><i>3. 피자</i></> : <><b>판정 결과</b><div className="mini-board"><i>★</i><i>○</i><i>×</i><i>○</i><i>★</i><i>○</i><i>×</i><i>○</i><i>★</i></div><strong>빙고 1줄 +3점!</strong></>}</div><h2>{current.title}</h2><p>{current.text}</p><div className="tutorial-nav"><button className="secondary" disabled={step === 0} onClick={() => setStep(value => value - 1)}>이전</button>{step < tutorialSteps.length - 1 ? <button onClick={() => setStep(value => value + 1)}>다음 →</button> : <button onClick={onClose}>게임 시작하기 →</button>}</div></section></div> }
function Waiting({ room, playerId, onStart, onTopics }) { const host = room.hostId === playerId; const [topics, setTopics] = useState(() => [...room.customTopics, '', '', ''].slice(0, 3)); const saveTopics = async () => { if (await onTopics(topics)) setTopics([...topics.filter(Boolean), '', '', ''].slice(0, 3)); }; return <section className="waiting"><div><small>초대 코드</small><h1>{room.code}</h1><p>친구에게 코드를 알려 주고 함께 입장하세요.</p></div><div className="waiting-players">{room.players.map(p => <span key={p.id}>{p.name}</span>)}</div>{host ? <><div className="custom-topics"><strong>방장 주제 설정 <small>(최대 3개)</small></strong>{topics.map((topic, index) => <input key={index} value={topic} maxLength="64" placeholder={`주제 ${index + 1} — 비워두면 랜덤`} onChange={e => setTopics(prev => prev.map((item, i) => i === index ? e.target.value : item))} />)}<button className="secondary" onClick={saveTopics}>주제 저장</button></div><button onClick={onStart}>게임 시작하기 →</button></> : <p className="host-wait">방장이 게임을 시작하면 바로 출발해요!</p>}<p className="rule-note">2–10명 · 3개 주제 · 주제마다 답 3개 · 75초<br/>8명부터 확장 규칙: 2–3명 ★ · 4–5명 ○ · 6명+ !</p></section> }
function SharingPanel({ sharing, selectedPlayer, isPresenter, onNext }) { const progress = `${Math.min(sharing.turnIndex + 1, sharing.totalTurns)} / ${sharing.totalTurns}`; return <><h2>답 공유 시간!</h2><p className="share-progress">전체 보드 공유 <b>{progress}</b> · 모든 답을 읽은 뒤 점수를 확인해요.</p>{sharing.selected ? <><p><b>{selectedPlayer?.name}</b> 님이 고른 답이에요.</p><div className={'shared-answer topic-color-' + sharing.selected.topicIndex}><small>TOPIC {sharing.selected.topicIndex + 1} · {sharing.selected.topic}</small><strong>{sharing.selected.answer}</strong></div>{isPresenter ? <button onClick={onNext}>읽었어요 · 다음 참가자 →</button> : <p className="host-wait">답을 읽은 뒤 다음 순서로 넘겨요.</p>}</> : isPresenter ? <><p>내 보드의 아직 공개하지 않은 답 하나를 골라, Zoom에서 읽어 주세요.</p><div className="burst">MY TURN!</div></> : <><p><b>{selectedPlayer?.name ?? '다음 참가자'}</b> 님 차례예요.</p><div className="burst">LISTEN!</div><p>답을 고르고 읽을 때까지 기다려 주세요.</p></>}</> }
function Board({ board, selectedSlots = [], onSelect, onShare, round, showMarks = true }) { return <div className="board">{Array.from({ length: 9 }, (_, i) => { const cell = board[i]; const selectedIndex = selectedSlots.indexOf(i); const canShare = cell && onShare && !cell.shared; const canSelect = !cell ? onSelect : canShare; const symbol = cell?.mark === 'star' ? '★' : cell?.mark === 'circle' ? '○' : cell?.mark === 'crowd' ? '!' : '×'; return <button className={'cell ' + (showMarks ? cell?.mark ?? '' : '') + (cell?.topicIndex !== undefined ? ` topic-color-${cell.topicIndex}` : '') + (selectedIndex >= 0 ? ' selected' : '') + (canSelect ? ' selectable' : '')} disabled={!canSelect} onClick={() => cell ? onShare?.(i) : onSelect?.(i)} key={i}><small>{i + 1}</small>{cell?.topicIndex !== undefined && <span className="cell-topic">T{cell.topicIndex + 1} · {cell.topic}</span>}{selectedIndex >= 0 && !cell && <em>{selectedIndex + 1}번 답</em>}{cell?.answer && <p>{cell.answer}</p>}{cell && showMarks && <b aria-label={cell.mark}>{symbol}</b>}</button>; })}</div> }
function Results({ room, playerId, onRematch }) { const sorted = [...room.players].sort((a, b) => b.score.points - a.score.points || b.score.lines - a.score.lines || b.score.stars - a.score.stars); return <section className="results"><div className="winner">{sorted[0]?.name} <span>WIN!</span></div><h1>마음이 통했어요!</h1><div className="rankings">{sorted.map((p, i) => <div key={p.id}><b>{i + 1}</b><span>{p.name}</span><strong>{p.score.points}점</strong><small>빙고 {p.score.lines} · 별 {p.score.stars}</small></div>)}</div>{room.hostId === playerId ? <button onClick={onRematch}>한 번 더 하기 →</button> : <p className="host-wait">방장이 재대결을 시작할 수 있어요.</p>}</section> }
createRoot(document.getElementById('root')).render(<App />);
